server:
  port: 8011
lala:
  test: remote_test_propety
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
        kafka:
          binder:
#            zkNodes: localhost
            brokers: localhost:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
#    root: DEBUG
    org.apache.kafka.clients: DEBUG